[project]
name = "paral-standalone"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "nuitka>=2.7.12",
    "paral>=0.2.4",
]
